CRSArrTimeHourDis = ["Night", "Evening", "Afternoon", "Morning", "EarlyMorning"]
CRSDepTimeHourDis = ["Evening", "Afternoon", "Night", "Morning", "EarlyMorning"]
DestCityName = [
    "Charleston, SC",
    "Newark, NJ",
    "Fayetteville, AR",
    "Houston, TX",
    "Monroe, LA",
    "Oklahoma City, OK",
    "Baton Rouge, LA",
    "Panama City, FL",
    "Chicago, IL",
    "Des Moines, IA",
    "Springfield, MO",
    "Savannah, GA",
    "Amarillo, TX",
    "Lexington, KY",
    "Indianapolis, IN",
    "Charleston/Dunbar, WV",
    "Huntsville, AL",
    "Atlanta, GA",
    "Detroit, MI",
    "Minneapolis, MN",
    "New York, NY",
    "Cleveland, OH",
    "White Plains, NY",
    "Boston, MA",
    "Richmond, VA",
    "Jackson/Vicksburg, MS",
    "Tulsa, OK",
    "Orlando, FL",
    "Birmingham, AL",
    "Louisville, KY",
    "Greer, SC",
    "Key West, FL",
    "Milwaukee, WI",
    "Newport News/Williamsburg, VA",
    "Augusta, GA",
    "Lincoln, NE",
    "Charlotte, NC",
    "Nashville, TN",
    "Philadelphia, PA",
    "Killeen, TX",
    "Evansville, IN",
    "Hartford, CT",
    "St. Louis, MO",
    "Cincinnati, OH",
    "Madison, WI",
    "Greensboro/High Point, NC",
    "Knoxville, TN",
    "Gulfport/Biloxi, MS",
    "Pittsburgh, PA",
    "Columbia, SC",
    "Valparaiso, FL",
    "Bloomington/Normal, IL",
    "Allentown/Bethlehem/Easton, PA",
    "Kalamazoo, MI",
    "Memphis, TN",
    "Tallahassee, FL",
    "Bristol/Johnson City/Kingsport, TN",
    "Grand Rapids, MI",
    "Norfolk, VA",
    "Gainesville, FL",
    "Buffalo, NY",
    "Myrtle Beach, SC",
    "Rochester, MN",
    "Appleton, WI",
    "Asheville, NC",
    "Omaha, NE",
    "Portland, ME",
    "Rochester, NY",
    "Raleigh/Durham, NC",
    "Cedar Rapids/Iowa City, IA",
    "Elmira/Corning, NY",
    "Columbus, OH",
    "Washington, DC",
    "Syracuse, NY",
    "Jacksonville, FL",
    "Moline, IL",
    "Trenton, NJ",
    "Islip, NY",
    "San Francisco, CA",
    "Phoenix, AZ",
    "Los Angeles, CA",
    "Miami, FL",
    "San Juan, PR",
    "Tampa, FL",
    "Las Vegas, NV",
    "Denver, CO",
    "New Orleans, LA",
    "Colorado Springs, CO",
    "Kansas City, MO",
    "Fort Myers, FL",
    "Seattle, WA",
    "Austin, TX",
    "Ontario, CA",
    "San Diego, CA",
    "Santa Ana, CA",
    "Salt Lake City, UT",
    "Portland, OR",
    "Providence, RI",
    "San Jose, CA",
    "West Palm Beach/Palm Beach, FL",
    "Albuquerque, NM",
    "Dallas/Fort Worth, TX",
    "San Antonio, TX",
    "Reno, NV",
    "Palm Springs, CA",
    "Baltimore, MD",
    "Fort Lauderdale, FL",
    "Oakland, CA",
    "Latrobe, PA",
    "Atlantic City, NJ",
    "Chattanooga, TN",
    "Little Rock, AR",
    "Akron, OH",
    "Charlottesville, VA",
    "Dayton, OH",
    "Daytona Beach, FL",
    "New Haven, CT",
    "Manchester, NH",
    "Jacksonville/Camp Lejeune, NC",
    "Melbourne, FL",
    "Mobile, AL",
    "Burlington, VT",
    "Sarasota/Bradenton, FL",
    "Pensacola, FL",
    "Wilmington, NC",
    "Scranton/Wilkes-Barre, PA",
    "Albany, NY",
    "Harrisburg, PA",
    "Fort Wayne, IN",
    "Lynchburg, VA",
    "Sioux Falls, SD",
    "Tucson, AZ",
    "Sacramento, CA",
    "Kona, HI",
    "Kahului, HI",
    "Lihue, HI",
    "Honolulu, HI",
    "Eagle, CO",
    "Jackson, WY",
    "Gunnison, CO",
    "Anchorage, AK",
    "Hilo, HI",
    "Bozeman, MT",
    "Spokane, WA",
    "Montrose/Delta, CO",
    "Billings, MT",
    "Eugene, OR",
    "Boise, ID",
    "Mission/McAllen/Edinburg, TX",
    "Guam, TT",
    "Wichita, KS",
    "Hayden, CO",
    "Burbank, CA",
    "Fresno, CA",
    "Santa Barbara, CA",
    "Medford, OR",
    "Dallas, TX",
    "Long Beach, CA",
    "El Paso, TX",
    "Harlingen/San Benito, TX",
    "Lubbock, TX",
    "Midland/Odessa, TX",
    "Corpus Christi, TX",
    "Flint, MI",
    "Brownsville, TX",
    "Lafayette, LA",
    "San Luis Obispo, CA",
    "Rapid City, SD",
    "Monterey, CA",
    "Bakersfield, CA",
    "Durango, CO",
    "Montgomery, AL",
    "Christiansted, VI",
    "Yakima, WA",
    "Bend/Redmond, OR",
    "Lewiston, ID",
    "Walla Walla, WA",
    "Wenatchee, WA",
    "Kalispell, MT",
    "Pullman, WA",
    "Mammoth Lakes, CA",
    "Pasco/Kennewick/Richland, WA",
    "Sun Valley/Hailey/Ketchum, ID",
    "Santa Rosa, CA",
    "Great Falls, MT",
    "Missoula, MT",
    "Bellingham, WA",
    "Fairbanks, AK",
    "Deadhorse, AK",
    "Helena, MT",
    "Unalaska, AK",
    "Charlotte Amalie, VI",
    "Bismarck/Mandan, ND",
    "Fayetteville, NC",
    "Roanoke, VA",
    "Fargo, ND",
    "Green Bay, WI",
    "Pago Pago, TT",
    "Hoolehua, HI",
    "Lanai, HI",
    "Kapalua, HI",
    "Grand Island, NE",
    "Roswell, NM",
    "Peoria, IL",
    "Bangor, ME",
    "Pocatello, ID",
    "Aberdeen, SD",
    "Alpena, MI",
    "Escanaba, MI",
    "Bemidji, MN",
    "Casper, WY",
    "Brainerd, MN",
    "Butte, MT",
    "St. George, UT",
    "Sault Ste. Marie, MI",
    "Marquette, MI",
    "Elko, NV",
    "Grand Junction, CO",
    "Ithaca/Cortland, NY",
    "Cody, WY",
    "Hibbing, MN",
    "Binghamton, NY",
    "Twin Falls, ID",
    "Pellston, MI",
    "Rhinelander, WI",
    "International Falls, MN",
    "Iron Mountain/Kingsfd, MI",
    "Aspen, CO",
    "Flagstaff, AZ",
    "Yuma, AZ",
    "Santa Fe, NM",
    "Traverse City, MI",
    "La Crosse, WI",
    "Meridian, MS",
    "Hattiesburg/Laurel, MS",
    "Bullhead City, AZ",
    "South Bend, IN",
    "Columbus, MS",
    "Saginaw/Bay City/Midland, MI",
    "Dothan, AL",
    "Lansing, MI",
    "State College, PA",
    "Newburgh/Poughkeepsie, NY",
    "Erie, PA",
    "Duluth, MN",
    "Shreveport, LA",
    "Idaho Falls, ID",
    "Williston, ND",
    "Grand Forks, ND",
    "Minot, ND",
    "Pueblo, CO",
    "Hancock/Houghton, MI",
    "Clarksburg/Fairmont, WV",
    "Springfield, IL",
    "Rock Springs, WY",
    "Jamestown, ND",
    "Devils Lake, ND",
    "Gillette, WY",
    "Eau Claire, WI",
    "Hays, KS",
    "Cedar City, UT",
    "Toledo, OH",
    "Cape Girardeau, MO",
    "Muskegon, MI",
    "Paducah, KY",
    "Quincy, IL",
    "Laramie, WY",
    "North Bend/Coos Bay, OR",
    "Redding, CA",
    "Columbia, MO",
    "Arcata/Eureka, CA",
    "Mosinee, WI",
    "Fort Smith, AR",
    "Lake Charles, LA",
    "Alexandria, LA",
    "College Station/Bryan, TX",
    "Laredo, TX",
    "Hobbs, NM",
    "Dubuque, IA",
    "Manhattan/Ft. Riley, KS",
    "Waco, TX",
    "Joplin, MO",
    "San Angelo, TX",
    "Lawton/Fort Sill, OK",
    "Beaumont/Port Arthur, TX",
    "Tyler, TX",
    "Champaign/Urbana, IL",
    "Aguadilla, PR",
    "Niagara Falls, NY",
    "Plattsburgh, NY",
    "Dickinson, ND",
    "Bethel, AK",
    "Barrow, AK",
    "Yakutat, AK",
    "Cordova, AK",
    "Juneau, AK",
    "Ketchikan, AK",
    "Sitka, AK",
    "Petersburg, AK",
    "Wrangell, AK",
    "Nome, AK",
    "Kotzebue, AK",
    "Adak Island, AK",
    "Kodiak, AK",
    "Columbus, GA",
    "Brunswick, GA",
    "Valdosta, GA",
    "Albany, GA",
    "New Bern/Morehead/Beaufort, NC",
    "Scottsbluff, NE",
    "Ponce, PR",
    "Worcester, MA",
    "Wichita Falls, TX",
    "Sioux City, IA",
    "Abilene, TX",
    "Garden City, KS",
    "Texarkana, AR",
    "Waterloo, IA",
    "Saipan, TT",
    "Rota, TT",
    "Watertown, NY",
    "Greenville, NC",
    "Williamsport, PA",
    "Salisbury, MD",
    "Ashland, WV",
    "Florence, SC",
    "Hilton Head, SC",
    "St. Petersburg, FL",
    "Belleville, IL",
    "Sanford, FL",
    "Owensboro, KY",
    "Punta Gorda, FL",
    "Concord, NC",
    "Ogden, UT",
    "Rockford, IL",
    "Provo, UT",
    "Youngstown/Warren, OH",
    "Stockton, CA",
    "Portsmouth, NH",
    "Ogdensburg, NY",
    "St. Cloud, MN",
    "Santa Maria, CA",
    "Hagerstown, MD",
    "Longview, TX",
    "Stillwater, OK",
    "Martha's Vineyard, MA",
    "Nantucket, MA",
    "Kearney, NE",
    "Vernal, UT",
    "Staunton, VA",
    "Lewisburg, WV",
    "Salina, KS",
    "Liberal, KS",
    "Moab, UT",
    "North Platte, NE",
    "Prescott, AZ",
    "Branson, MO",
    "Presque Isle/Houlton, ME",
    "Cheyenne, WY",
    "Del Rio, TX",
    "West Yellowstone, MT",
    "Hyannis, MA",
    "Gustavus, AK",
    "Dillingham, AK",
    "King Salmon, AK",
    "CONCORD, NC",
    "Everett, WA",
    "Pierre, SD",
    "Watertown, SD",
    "Riverton/Lander, WY",
    "Sheridan, WY",
    "Cold Bay, AK",
    "Decatur, IL",
    "Dodge City, KS",
    "Alamosa, CO",
    "Victoria, TX",
    "Johnstown, PA",
    "Wilmington, DE",
    "Mason City, IA",
    "Fort Dodge, IA",
    "Fort Leonard Wood, MO",
    "Bishop, CA",
]
OriginCityName = [
    "Newark, NJ",
    "Providence, RI",
    "Chicago, IL",
    "Lafayette, LA",
    "Houston, TX",
    "Gulfport/Biloxi, MS",
    "Tulsa, OK",
    "Greer, SC",
    "Mobile, AL",
    "Huntsville, AL",
    "Little Rock, AR",
    "Corpus Christi, TX",
    "Des Moines, IA",
    "Burlington, VT",
    "Atlanta, GA",
    "Charleston/Dunbar, WV",
    "Lexington, KY",
    "Nashville, TN",
    "Minneapolis, MN",
    "Richmond, VA",
    "Cleveland, OH",
    "Detroit, MI",
    "White Plains, NY",
    "Birmingham, AL",
    "Jackson/Vicksburg, MS",
    "Louisville, KY",
    "Orlando, FL",
    "Columbia, SC",
    "New York, NY",
    "Fayetteville, AR",
    "Newport News/Williamsburg, VA",
    "Lincoln, NE",
    "Cincinnati, OH",
    "Charleston, SC",
    "Tallahassee, FL",
    "Pittsburgh, PA",
    "Charlotte, NC",
    "Philadelphia, PA",
    "Hartford, CT",
    "Savannah, GA",
    "Panama City, FL",
    "Valparaiso, FL",
    "St. Louis, MO",
    "Killeen, TX",
    "Key West, FL",
    "Milwaukee, WI",
    "Springfield, MO",
    "Evansville, IN",
    "Knoxville, TN",
    "Bloomington/Normal, IL",
    "Allentown/Bethlehem/Easton, PA",
    "Boston, MA",
    "Omaha, NE",
    "Greensboro/High Point, NC",
    "Memphis, TN",
    "Moline, IL",
    "Kalamazoo, MI",
    "Bristol/Johnson City/Kingsport, TN",
    "Augusta, GA",
    "Gainesville, FL",
    "Grand Rapids, MI",
    "Buffalo, NY",
    "Myrtle Beach, SC",
    "Raleigh/Durham, NC",
    "Appleton, WI",
    "Rochester, NY",
    "Asheville, NC",
    "Chattanooga, TN",
    "Norfolk, VA",
    "Madison, WI",
    "Portland, ME",
    "Baton Rouge, LA",
    "Rochester, MN",
    "Elmira/Corning, NY",
    "Columbus, OH",
    "Cedar Rapids/Iowa City, IA",
    "Harrisburg, PA",
    "Syracuse, NY",
    "Jacksonville, FL",
    "Washington, DC",
    "Fort Myers, FL",
    "Tampa, FL",
    "Denver, CO",
    "Islip, NY",
    "Las Vegas, NV",
    "Austin, TX",
    "Trenton, NJ",
    "San Diego, CA",
    "Dallas/Fort Worth, TX",
    "Salt Lake City, UT",
    "Albuquerque, NM",
    "Los Angeles, CA",
    "San Francisco, CA",
    "Phoenix, AZ",
    "Miami, FL",
    "Oklahoma City, OK",
    "Colorado Springs, CO",
    "Ontario, CA",
    "Seattle, WA",
    "New Orleans, LA",
    "Santa Ana, CA",
    "Palm Springs, CA",
    "San Jose, CA",
    "Portland, OR",
    "Kansas City, MO",
    "West Palm Beach/Palm Beach, FL",
    "Indianapolis, IN",
    "San Antonio, TX",
    "San Juan, PR",
    "Reno, NV",
    "Baltimore, MD",
    "Fort Lauderdale, FL",
    "Niagara Falls, NY",
    "Latrobe, PA",
    "Atlantic City, NJ",
    "Akron, OH",
    "Daytona Beach, FL",
    "Dayton, OH",
    "New Haven, CT",
    "Manchester, NH",
    "Jacksonville/Camp Lejeune, NC",
    "Melbourne, FL",
    "Sarasota/Bradenton, FL",
    "Fayetteville, NC",
    "Charlottesville, VA",
    "Pensacola, FL",
    "Wilmington, NC",
    "Albany, NY",
    "Fort Wayne, IN",
    "Lynchburg, VA",
    "Toledo, OH",
    "Hayden, CO",
    "Bozeman, MT",
    "Eugene, OR",
    "Boise, ID",
    "Spokane, WA",
    "Tucson, AZ",
    "Honolulu, HI",
    "Kona, HI",
    "Kahului, HI",
    "Eagle, CO",
    "Sacramento, CA",
    "Gunnison, CO",
    "Mission/McAllen/Edinburg, TX",
    "Lihue, HI",
    "Anchorage, AK",
    "Aguadilla, PR",
    "Montrose/Delta, CO",
    "Billings, MT",
    "Jackson, WY",
    "Guam, TT",
    "Wichita, KS",
    "Hilo, HI",
    "Burbank, CA",
    "Medford, OR",
    "Santa Barbara, CA",
    "Fresno, CA",
    "Sioux Falls, SD",
    "Amarillo, TX",
    "Dallas, TX",
    "El Paso, TX",
    "Flint, MI",
    "Harlingen/San Benito, TX",
    "Lubbock, TX",
    "Long Beach, CA",
    "Midland/Odessa, TX",
    "Oakland, CA",
    "Brownsville, TX",
    "Peoria, IL",
    "Rapid City, SD",
    "Durango, CO",
    "Monterey, CA",
    "Bakersfield, CA",
    "San Luis Obispo, CA",
    "Grand Island, NE",
    "Montgomery, AL",
    "Christiansted, VI",
    "Yakima, WA",
    "Lewiston, ID",
    "Wenatchee, WA",
    "Bend/Redmond, OR",
    "Pullman, WA",
    "Walla Walla, WA",
    "Helena, MT",
    "Mammoth Lakes, CA",
    "Pasco/Kennewick/Richland, WA",
    "Missoula, MT",
    "Great Falls, MT",
    "Sun Valley/Hailey/Ketchum, ID",
    "Santa Rosa, CA",
    "Bellingham, WA",
    "Fairbanks, AK",
    "Deadhorse, AK",
    "Kalispell, MT",
    "Unalaska, AK",
    "Charlotte Amalie, VI",
    "Roanoke, VA",
    "Bismarck/Mandan, ND",
    "Scranton/Wilkes-Barre, PA",
    "Fargo, ND",
    "Green Bay, WI",
    "Pago Pago, TT",
    "Hoolehua, HI",
    "Lanai, HI",
    "Kapalua, HI",
    "Roswell, NM",
    "Bangor, ME",
    "Aberdeen, SD",
    "Grand Junction, CO",
    "Alpena, MI",
    "Escanaba, MI",
    "Pellston, MI",
    "Bemidji, MN",
    "Casper, WY",
    "Brainerd, MN",
    "Butte, MT",
    "Cedar City, UT",
    "Elko, NV",
    "St. George, UT",
    "Cody, WY",
    "Hibbing, MN",
    "Binghamton, NY",
    "Twin Falls, ID",
    "Marquette, MI",
    "Sault Ste. Marie, MI",
    "Rhinelander, WI",
    "Ithaca/Cortland, NY",
    "La Crosse, WI",
    "International Falls, MN",
    "Pocatello, ID",
    "Aspen, CO",
    "Flagstaff, AZ",
    "Yuma, AZ",
    "Traverse City, MI",
    "Meridian, MS",
    "Hattiesburg/Laurel, MS",
    "Santa Fe, NM",
    "Bullhead City, AZ",
    "South Bend, IN",
    "Columbus, MS",
    "Lansing, MI",
    "State College, PA",
    "Newburgh/Poughkeepsie, NY",
    "Erie, PA",
    "Iron Mountain/Kingsfd, MI",
    "Duluth, MN",
    "Williston, ND",
    "Saginaw/Bay City/Midland, MI",
    "Minot, ND",
    "Monroe, LA",
    "Dothan, AL",
    "Shreveport, LA",
    "Hancock/Houghton, MI",
    "Gillette, WY",
    "Clarksburg/Fairmont, WV",
    "Rock Springs, WY",
    "Pueblo, CO",
    "Muskegon, MI",
    "Springfield, IL",
    "Devils Lake, ND",
    "Jamestown, ND",
    "Laramie, WY",
    "Hays, KS",
    "Paducah, KY",
    "Idaho Falls, ID",
    "Arcata/Eureka, CA",
    "Grand Forks, ND",
    "Quincy, IL",
    "Eau Claire, WI",
    "Cape Girardeau, MO",
    "North Bend/Coos Bay, OR",
    "Mosinee, WI",
    "Redding, CA",
    "Columbia, MO",
    "Fort Smith, AR",
    "Laredo, TX",
    "College Station/Bryan, TX",
    "Lake Charles, LA",
    "Alexandria, LA",
    "Hobbs, NM",
    "Dubuque, IA",
    "Waco, TX",
    "Tyler, TX",
    "Manhattan/Ft. Riley, KS",
    "Joplin, MO",
    "Champaign/Urbana, IL",
    "San Angelo, TX",
    "Lawton/Fort Sill, OK",
    "Stillwater, OK",
    "Beaumont/Port Arthur, TX",
    "Sioux City, IA",
    "Plattsburgh, NY",
    "Dickinson, ND",
    "Kodiak, AK",
    "Bethel, AK",
    "Barrow, AK",
    "Ketchikan, AK",
    "Juneau, AK",
    "Yakutat, AK",
    "Cordova, AK",
    "Sitka, AK",
    "Wrangell, AK",
    "Petersburg, AK",
    "Nome, AK",
    "Kotzebue, AK",
    "Adak Island, AK",
    "Columbus, GA",
    "Brunswick, GA",
    "Valdosta, GA",
    "Albany, GA",
    "Scottsbluff, NE",
    "Ponce, PR",
    "Worcester, MA",
    "Wichita Falls, TX",
    "Abilene, TX",
    "Longview, TX",
    "Garden City, KS",
    "Waterloo, IA",
    "Saipan, TT",
    "Rota, TT",
    "Ashland, WV",
    "Greenville, NC",
    "New Bern/Morehead/Beaufort, NC",
    "Watertown, NY",
    "Salisbury, MD",
    "Williamsport, PA",
    "Florence, SC",
    "Hilton Head, SC",
    "St. Petersburg, FL",
    "Hagerstown, MD",
    "Sanford, FL",
    "Rockford, IL",
    "Owensboro, KY",
    "Punta Gorda, FL",
    "Concord, NC",
    "Ogden, UT",
    "Provo, UT",
    "Belleville, IL",
    "Stockton, CA",
    "Portsmouth, NH",
    "Ogdensburg, NY",
    "St. Cloud, MN",
    "Santa Maria, CA",
    "Youngstown/Warren, OH",
    "Texarkana, AR",
    "Nantucket, MA",
    "Martha's Vineyard, MA",
    "Lewisburg, WV",
    "Staunton, VA",
    "North Platte, NE",
    "Kearney, NE",
    "Salina, KS",
    "Vernal, UT",
    "Moab, UT",
    "Liberal, KS",
    "Prescott, AZ",
    "Branson, MO",
    "Presque Isle/Houlton, ME",
    "Cheyenne, WY",
    "Del Rio, TX",
    "West Yellowstone, MT",
    "Hyannis, MA",
    "Gustavus, AK",
    "King Salmon, AK",
    "Dillingham, AK",
    "CONCORD, NC",
    "Everett, WA",
    "Pierre, SD",
    "Watertown, SD",
    "Sheridan, WY",
    "Riverton/Lander, WY",
    "Cold Bay, AK",
    "Dodge City, KS",
    "Decatur, IL",
    "Alamosa, CO",
    "Victoria, TX",
    "Johnstown, PA",
    "Wilmington, DE",
    "Mason City, IA",
    "Fort Leonard Wood, MO",
    "Fort Dodge, IA",
    "Bishop, CA",
]
Marketing_AN = ["UA", "DL", "F9", "NK", "AA", "WN", "AS", "HA", "VX", "B6", "G4"]
